# ── Adivery Ads (the only network — AdMob removed) ────────────────────────────
# The AAR ships its own consumer rules (auto-merged), but keep them explicitly
# for release builds: the SDK uses reflection + a JS bridge (WebView mediation)
# and the reward callback must survive R8.
-keep class com.adivery.sdk.** { *; }
-keepattributes JavascriptInterface
-keep class android.webkit.JavascriptInterface { *; }
# Adivery's AAR statically references optional mediation networks (MBridge /
# Mintegral, AdMob, Unity, ...) that this app does not ship. Generated by AGP
# R8 — suppress.
-dontwarn com.mbridge.msdk.**
-dontwarn com.google.android.gms.ads.**
-dontwarn com.unity3d.ads.**
-dontwarn com.unity3d.services.**
